#!/usr/bin/env bash

if [[ ${1} = "-s" ]]; then
    # Capture entire screen
    params="-window root"
fi

screenshot_folder=~/Pictures/screenshots/
file_path=${screenshot_folder}$( date '+%Y-%m-%d_%H-%M-%S' )_screenshot.png

# Take the screenshot
import ${params} ${file_path}
# Copy to clipboard
xclip -selection clipboard -target image/png -i ${file_path}
